
url: https://www.rathboma.com
name: Rathboma's blog
plugins:
  - 'jekyll-sitemap'
version: 2.4
description: Ramblings of an indie open source business owner.
exclude: ['ideas', 'drafts']
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      sitemap: true
  -
    scope:
      type: "posts"
      path: ""
    values:
      is_post: true
      subject: "unclassified"
