
url: https://blog.matthewrathbone.com
name: Matthew Rathbone's Website
plugins: 
  - 'jekyll-paginate'
  - 'jekyll-sitemap'
  - 'jekyll-assets'
version: 2.4
description: Tutorials and guides for big data technologies. I write about Scala, Spark, Hadoop, HDFS, and more.
paginate: 5
exclude: ['ideas', 'drafts']
markdown: kramdown
kramdown:
  syntax_highlighter: rogue
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      sitemap: true
  -
    scope:
      type: "posts"
      path: ""
    values:
      is_post: true